name: Sync Fork with Rebase

on:
  schedule:
    - cron: '0 0 * * *' # Esegue ogni giorno a mezzanotte
  workflow_dispatch: # Permette di eseguire manualmente il workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Serve per il push dei cambiamenti
      pull-requests: write # Utile per creare PR se necessario

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with upstream (External Repo)
        env:
          GH_PAT: ${{ secrets.EXTERNAL_REPO_PAT }}
        run: |
          # Use dynamic variables to get the original repository URL
          # Note: The PAT is needed for external repo access
          UPSTREAM_URL="https://${{ env.GH_PAT }}@github.com/${{ github.event.repository.source.owner.login }}/${{ github.event.repository.source.name }}.git"
          
          # Add and update the 'upstream' remote
          git remote add upstream $UPSTREAM_URL || git remote set-url upstream $UPSTREAM_URL
          
          # Fetch and rebase
          git fetch upstream
          git rebase upstream/main

      - name: Push changes
        run: |
          git push origin main --force-with-lease
